name: Trigger Databricks Train+Infer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run_databricks_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Databricks Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          JOB_ID: ${{ secrets.DATABRICKS_JOB_ID }}
        run: |
          pip install databricks-sdk
          python - << 'PY'
          import os
          from databricks.sdk import WorkspaceClient

          w = WorkspaceClient(
              host=os.environ["DATABRICKS_HOST"],
              token=os.environ["DATABRICKS_TOKEN"]
          )

          job_id = int(os.environ["JOB_ID"])
          run = w.jobs.run_now(job_id=job_id)

          # Print run id for traceability
          print(f"Triggered Databricks job_id={job_id}, run_id={run.run_id}")
          PY
